# <span style="color:#00bfff">Álgebra Lineal con Python</span>

## <span style="color:#00bfff;">1.</span> Suma y resta de matrices

In [1]:
import numpy as np

# Definir matrices A y B
A = np.array([[2, 4], [1, 3]])
B = np.array([[5, 1], [2, 6]])

# Suma de matrices
suma = A + B
print(f"Suma de matrices (A + B):\n{suma}")

# Resta de matrices
resta = A - B
print(f"\nResta de matrices (A - B):\n{resta}")

Suma de matrices (A + B):
[[7 5]
 [3 9]]

Resta de matrices (A - B):
[[-3  3]
 [-1 -3]]


## <span style="color:#00bfff;">2.</span> Producto punto

In [2]:
# Producto matricial
producto_matrices = np.dot(A, B)
print(f"\nProducto matricial (A·B):\n {producto_matrices}") 


Producto matricial (A·B):
 [[18 26]
 [11 19]]


## <span style="color:#00bfff;">3.</span> Trasposición e inversa de una Matriz

In [3]:
# Transpuesta de A
transpuesta_A = A.T
print(f"\nTranspuesta de A:\n{transpuesta_A}")

# Inversa de A (si es invertible)
if np.linalg.det(A) != 0:  # Verificamos que sea invertible
    inversa_A = np.linalg.inv(A)
    print(f"\nInversa de A:\n{inversa_A}")
else:
    print("\nLa matriz A no es invertible")


Transpuesta de A:
[[2 1]
 [4 3]]

Inversa de A:
[[ 1.5 -2. ]
 [-0.5  1. ]]
