<div style="background:linear-gradient(135deg, rgba(249,112,102,0.18), rgba(249,112,102,0.02)); border-left:6px solid #F97066; border-radius:10px; padding:20px 24px; margin-bottom:20px;">
<h1 style="margin:0; color:#F97066; font-size:1.8em;">🔢 Álgebra Lineal con Python</h1>
<p style="margin:6px 0 0; opacity:0.8;">Unidad 3 — Fundamentos matemáticos para Machine Learning</p>
</div>

El álgebra lineal es, en gran medida, el lenguaje matemático del *Machine Learning*: un conjunto de datos se representa como una matriz (filas = observaciones, columnas = variables), un ejemplo individual como un vector, y los parámetros de un modelo (pesos, coeficientes) también se organizan como vectores o matrices. Operaciones como la suma, el producto o la inversa de matrices son, en realidad, los pasos que un modelo ejecuta internamente para aprender y hacer predicciones.

<div style="border:1px solid rgba(14,165,233,0.35); border-radius:10px; padding:14px 20px; margin:16px 0 24px; background:rgba(14,165,233,0.04);">
<strong>📑 Contenido de esta guía</strong>
<ol style="margin:8px 0 0; padding-left:20px;">
<li><a href="#vectores">Vectores: operaciones básicas y norma</a></li>
<li><a href="#espacios-vectoriales">Espacios vectoriales: dónde "viven" los vectores</a></li>
<li><a href="#suma-resta">Suma y resta de matrices</a></li>
<li><a href="#producto-punto">Producto punto y producto matricial</a></li>
<li><a href="#matriz-vector">Producto matriz-vector</a></li>
<li><a href="#transpuesta-inversa">Transposición e inversa de una matriz</a></li>
<li><a href="#cierre">Cierre y próximos pasos</a></li>
</ol>
</div>

<a id="vectores"></a>

## <span style="color:#F97066;">1.</span> Vectores: operaciones básicas y norma

Un **vector** es una lista ordenada de números que representa un punto o una dirección en un espacio de $n$ dimensiones. En Machine Learning, cada ejemplo de un conjunto de datos suele representarse como un vector de características (*feature vector*): por ejemplo, una casa descrita por su área, número de habitaciones y antigüedad es el vector $[120, 3, 8]$.

A continuación, se definen dos vectores y se calculan algunas operaciones básicas, incluyendo su **norma** (magnitud o longitud del vector), que corresponde a la distancia euclidiana entre el vector y el origen. La norma es la base de métricas de distancia y similitud ampliamente usadas en Machine Learning (por ejemplo, en el algoritmo K-Vecinos Más Cercanos o en términos de regularización).

In [1]:
import numpy as np

# Definir dos vectores
v1 = np.array([3, 4])
v2 = np.array([1, 2])

# Suma de vectores
print(f"Suma de vectores (v1 + v2): {v1 + v2}")

# Multiplicación por un escalar
print(f"v1 multiplicado por 2: {v1 * 2}")

# Norma (magnitud) de un vector: distancia euclidiana al origen
norma_v1 = np.linalg.norm(v1)
print(f"Norma de v1: {norma_v1}")

Suma de vectores (v1 + v2): [4 6]
v1 multiplicado por 2: [6 8]
Norma de v1: 5.0


<a id="espacios-vectoriales"></a>

## <span style="color:#F97066;">2.</span> Espacios vectoriales: dónde "viven" los vectores

Un **espacio vectorial** es un conjunto de vectores en el que están definidas dos operaciones — la suma de vectores y la multiplicación por un escalar — de modo que el resultado de cualquiera de las dos siempre es, a su vez, otro vector del mismo conjunto. El ejemplo más común en Machine Learning es $\mathbb{R}^n$: el conjunto de todas las listas de $n$ números reales, como los vectores de características ya vistos en la sección anterior.

Todo espacio vectorial tiene una **base**: un conjunto mínimo de vectores a partir del cual, mediante combinaciones lineales ($a_1 v_1 + a_2 v_2 + \dots$), se puede construir cualquier otro vector del espacio. El número de vectores de la base es la **dimensión** del espacio. Por ejemplo, en $\mathbb{R}^2$ la base estándar es $\{(1,0), (0,1)\}$, y cualquier vector $(a,b)$ se escribe como $a\cdot(1,0) + b\cdot(0,1)$.

El conjunto de **todas** las combinaciones lineales posibles de un grupo de vectores se llama su **span**, y forma un **subespacio**: un espacio vectorial más pequeño contenido dentro de uno más grande. Dos vectores linealmente independientes en $\mathbb{R}^3$ generan, por ejemplo, un plano que pasa por el origen — un subespacio de dimensión 2 dentro de un espacio de dimensión 3. A continuación, una visualización interactiva de exactamente esta idea.

In [2]:
import numpy as np
import plotly.graph_objects as go

# Dos vectores linealmente independientes en R^3
v1 = np.array([2, 0, 1])
v2 = np.array([0, 2, 1])
# Un tercer vector que NO pertenece al plano (subespacio) generado por v1 y v2
v3 = np.array([0, 0, 3])

# 1. Generar el plano formado por todas las combinaciones lineales s*v1 + t*v2 (el span de v1 y v2)
s = np.linspace(-1.5, 1.5, 10)
t = np.linspace(-1.5, 1.5, 10)
S, T = np.meshgrid(s, t)
X = S * v1[0] + T * v2[0]
Y = S * v1[1] + T * v2[1]
Z = S * v1[2] + T * v2[2]

fig = go.Figure()

# El plano (subespacio) generado por v1 y v2
fig.add_trace(go.Surface(
    x=X, y=Y, z=Z,
    colorscale=[[0, "#0EA5E9"], [1, "#0EA5E9"]], opacity=0.35, showscale=False,
    name="Span(v1, v2)",
))

# Los vectores base v1 y v2, como flechas desde el origen
for v, nombre in [(v1, "v1"), (v2, "v2")]:
    fig.add_trace(go.Scatter3d(
        x=[0, v[0]], y=[0, v[1]], z=[0, v[2]],
        mode="lines+markers", line=dict(color="#F97066", width=6),
        marker=dict(size=4, color="#F97066"), name=nombre,
    ))

# Algunas combinaciones lineales a*v1 + b*v2 (puntos sobre el plano)
combinaciones = [(1, 0.5), (-1, 1), (0.5, -1), (1.5, 1.5)]
for a, b in combinaciones:
    punto = a * v1 + b * v2
    fig.add_trace(go.Scatter3d(
        x=[punto[0]], y=[punto[1]], z=[punto[2]],
        mode="markers", marker=dict(size=5, color="#14B8A6"),
        name=f"{a}·v1 + {b}·v2",
    ))

# v3: un vector que NO está en el span de v1 y v2
fig.add_trace(go.Scatter3d(
    x=[0, v3[0]], y=[0, v3[1]], z=[0, v3[2]],
    mode="lines+markers", line=dict(color="#6366F1", width=6),
    marker=dict(size=4, color="#6366F1"), name="v3 (fuera del span)",
))

fig.update_layout(
    title="Espacio generado (span) por dos vectores en R³",
    scene=dict(xaxis_title="x", yaxis_title="y", zaxis_title="z"),
    width=800, height=600, margin=dict(l=0, r=0, b=0, t=40),
)
fig.show()

# Verificación algebraica: el rango de [v1, v2] es 2 (independientes, generan un plano);
# al agregar v3 el rango sube a 3, confirmando que v3 no pertenece a ese plano.
print(f"Rango de [v1, v2]: {np.linalg.matrix_rank(np.array([v1, v2]))}")
print(f"Rango de [v1, v2, v3]: {np.linalg.matrix_rank(np.array([v1, v2, v3]))}")

Rango de [v1, v2]: 2
Rango de [v1, v2, v3]: 3


El plano celeste de la figura es exactamente el conjunto de todos los puntos $a\cdot v_1 + b\cdot v_2$ para cualquier par de números $a, b$: el **span** de $v_1$ y $v_2$. Los puntos verdes son solo algunas de esas combinaciones. El vector $v_3$ (índigo), en cambio, no puede escribirse como combinación de $v_1$ y $v_2$ — no está sobre el plano —, lo que se confirma arriba con el rango de la matriz: pasa de 2 a 3 al incluir $v_3$. Al agregarlo, el span pasa a cubrir todo $\mathbb{R}^3$: exactamente por eso hacen falta 3 vectores independientes para generar un espacio de dimensión 3.

<div style="border-left:4px solid #6366F1; background:rgba(99,102,241,0.08); border-radius:6px; padding:10px 16px; margin:16px 0;">
<strong>📝 Nota — por qué esto importa en IA</strong><br>
La idea de espacio vectorial aparece en casi todos los temas de este curso:
<ul style="margin:8px 0 0; padding-left:20px;">
<li>El <strong>espacio de características</strong> (<em>feature space</em>) de un dataset es un espacio vectorial de dimensión igual al número de variables: cada ejemplo es un punto de ese espacio.</li>
<li>Los <strong>embeddings</strong> de palabras u oraciones (vistos en <code>../../Unidad 4/5-procesamiento-lenguaje-natural.ipynb</code> y <code>../../Unidad 4/6-transformers.ipynb</code>) son vectores en un espacio de alta dimensión, donde la cercanía geométrica entre dos vectores codifica qué tan similares son sus significados.</li>
<li><strong>PCA</strong> (visto en <code>5-data-preprocessing.ipynb</code> y en <code>../4-aprendizaje-no-supervisado.ipynb</code>) encuentra una base nueva — más útil — para ese mismo espacio: sus componentes principales son, precisamente, un subespacio de menor dimensión que conserva la mayor parte de la información original.</li>
<li>El <strong>espacio de parámetros</strong> de un modelo (todos sus pesos y sesgos) también es un espacio vectorial: el descenso de gradiente, visto en <code>2-gradiente-descendiente.ipynb</code>, es un recorrido dentro de ese espacio en busca del punto de menor error.</li>
<li>Medidas como la <strong>norma</strong> (ya vista en la sección anterior) y la <strong>similitud coseno</strong> dependen directamente de la estructura geométrica del espacio vectorial, y son la base de algoritmos como k-Vecinos Más Cercanos o la búsqueda de embeddings similares.</li>
</ul>
</div>

<a id="suma-resta"></a>

## <span style="color:#F97066;">3.</span> Suma y resta de matrices

Una **matriz** es una tabla de números organizada en filas y columnas; en Machine Learning, un conjunto de datos completo suele representarse como una matriz, donde cada fila es una observación y cada columna una variable. La suma y la resta de matrices son operaciones **elemento a elemento** (ambas matrices deben tener las mismas dimensiones) y aparecen constantemente al actualizar los parámetros de un modelo: por ejemplo, la regla de actualización del descenso de gradiente consiste, precisamente, en restarle a la matriz de pesos actual una fracción del gradiente.

In [3]:
import numpy as np

# Definir matrices A y B
A = np.array([[2, 4], [1, 3]])
B = np.array([[5, 1], [2, 6]])

# Suma de matrices
suma = A + B
print(f"Suma de matrices (A + B):\n{suma}")

# Resta de matrices
resta = A - B
print(f"\nResta de matrices (A - B):\n{resta}")

Suma de matrices (A + B):
[[7 5]
 [3 9]]

Resta de matrices (A - B):
[[-3  3]
 [-1 -3]]


<a id="producto-punto"></a>

## <span style="color:#F97066;">4.</span> Producto punto y producto matricial

El **producto punto** (o producto escalar) entre dos vectores multiplica sus componentes correspondientes y suma los resultados, produciendo un único número (escalar). Es la operación central detrás de la similitud coseno y de la salida de una neurona: cada neurona calcula, esencialmente, el producto punto entre sus entradas y sus pesos.

Cuando se aplica `np.dot()` sobre dos **matrices** (en lugar de dos vectores), la operación resultante es el **producto matricial**, que combina filas de la primera matriz con columnas de la segunda. A continuación se muestran ambos casos.

In [4]:
# Producto punto entre dos vectores (resultado: un escalar)
producto_punto_vectores = np.dot(v1, v2)
print(f"Producto punto (v1 · v2): {producto_punto_vectores}")

Producto punto (v1 · v2): 1


In [5]:
# Producto matricial
producto_matrices = np.dot(A, B)
print(f"\nProducto matricial (A·B):\n {producto_matrices}") 


Producto matricial (A·B):
 [[18 26]
 [11 19]]


<a id="matriz-vector"></a>

## <span style="color:#F97066;">5.</span> Producto matriz-vector

El caso particular del producto matricial más usado en Machine Learning es el **producto de una matriz por un vector**: $y = Ax$. Esta operación representa una **transformación lineal** aplicada al vector $x$, y es exactamente lo que calcula una capa de una red neuronal (antes de la función de activación) o la predicción de un modelo de regresión lineal ($\hat{y} = Xw$).

<span style="background:#0EA5E9;color:#ffffff;padding:4px 14px;border-radius:14px;font-size:0.75em;">🧪 EJERCICIO</span>

Ejecute la siguiente celda y observe cómo la matriz `A` transforma al vector `x` en un nuevo vector.

In [6]:
# Vector de entrada
x = np.array([1, 2])

# Producto matriz-vector: y = A x
y = A.dot(x)
print(f"A · x = {y}")

A · x = [10  7]


<a id="transpuesta-inversa"></a>

## <span style="color:#F97066;">6.</span> Transposición e inversa de una matriz

La **transpuesta** de una matriz intercambia filas por columnas; se utiliza, por ejemplo, para adaptar las dimensiones de dos matrices antes de multiplicarlas. La **inversa** de una matriz $A$ (denotada $A^{-1}$) es aquella que, multiplicada por $A$, produce la matriz identidad; solo existe si $A$ es cuadrada y su determinante es distinto de cero.

Ambas operaciones son la base de la **ecuación normal**, la fórmula cerrada que resuelve una regresión lineal sin necesidad de descenso de gradiente: $w = (X^TX)^{-1}X^Ty$, donde $X^T$ es la transpuesta de la matriz de datos y $(X^TX)^{-1}$ es la inversa del producto matricial resultante.

In [7]:
# Transpuesta de A
transpuesta_A = A.T
print(f"\nTranspuesta de A:\n{transpuesta_A}")

# Inversa de A (si es invertible)
if np.linalg.det(A) != 0:  # Verificamos que sea invertible
    inversa_A = np.linalg.inv(A)
    print(f"\nInversa de A:\n{inversa_A}")
else:
    print("\nLa matriz A no es invertible")


Transpuesta de A:
[[2 1]
 [4 3]]

Inversa de A:
[[ 1.5 -2. ]
 [-0.5  1. ]]


---

<a id="cierre"></a>

# <span style="color:#F97066;">🎯 Cierre y próximos pasos</span>

<div style="border-left:4px solid #14B8A6; background:rgba(20,184,166,0.08); border-radius:6px; padding:10px 16px; margin:16px 0;">
<strong>✅ Resumen</strong><br>
En este notebook se presentaron las operaciones de álgebra lineal más utilizadas en Machine Learning:

- Vectores: suma, multiplicación por escalar y norma (magnitud).
- Espacios vectoriales: base, dimensión, combinación lineal y subespacios (span), y su relación con el espacio de características, los embeddings, PCA y el espacio de parámetros de un modelo.
- Suma y resta de matrices, elemento a elemento.
- Producto punto entre vectores y producto matricial entre matrices.
- Producto matriz-vector (<code>y = Ax</code>), la base de una capa lineal o una regresión lineal.
- Transposición e inversa de una matriz, componentes de la ecuación normal de la regresión lineal.

</div>

<div style="border:1px solid rgba(14,165,233,0.35); border-radius:10px; padding:14px 20px; margin:16px 0; background:rgba(14,165,233,0.04);">
<strong>➡️ Continúe con</strong>
<ul style="margin:8px 0 0; padding-left:20px;">
<li><code>2-gradiente-descendiente.ipynb</code> — el descenso de gradiente utiliza, en cada iteración, exactamente las operaciones vectoriales presentadas aquí (resta de vectores, producto punto, norma del gradiente) para ajustar los parámetros de un modelo.</li>
</ul>
</div>